Bruk tidligere labber, og Cloud 9 miljøet deres til å ;

Lag en ny Spring Boot applikasjon, eller en eksisterende om det er enklere
Lag en Dockerfile, eller bruk en eksisterende til å pakke applikasjonen deres som et Docker Image
Publiser deres Docker Image til Amazon Elastic Container Registry
Når applikasjonen først ligger i ECR, så er det enkelt å gjøre denne tilgjengelig med PAAS tjenesten AWS App runner.
Forsøk det!
